version: '3.1'
services:
  db:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    command: [
      "--log-bin=mysql-bin",
      "--server-id=1",
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci",
      "--innodb_flush_log_at_trx_commit=1",
      "--sync_binlog=1"
      ]
    environment:
      MYSQL_ROOT_PASSWORD: 12wsxCDE#
      MYSQL_DATABASE: teleport
      MYSQL_USER: teleport
      MYSQL_PASSWORD: 12wsxCDE#
    ports:
      - 3306:3306

  teleport:
    build: .
    image: teleport
    container_name: teleport
    depends_on:
      - db
    tty: true
    command: bash -c "/usr/local/teleport/start.sh && top"
    volumes:
      - ./conf/web.ini:/usr/local/teleport/data/etc/web.ini 
    ports:
      - 7190:7190
